// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TL.ExemploCQRS.Domain.Entities;
using TL.ExemploCQRS.Infrastructure.Data;

#nullable disable

namespace TL.ExemploCQRS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TL.ExemploCQRS.Domain.Entities.Product", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").ValueGeneratedNever();
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<int>("StockQuantity").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("IsDeleted").HasDatabaseName("IX_Products_IsDeleted");
                b.HasIndex("Name").HasDatabaseName("IX_Products_Name");
                b.ToTable("Products");
                b.HasAnnotation("QueryFilter", "p => !EF.Property<bool>(p, \"IsDeleted\")");
            });

            modelBuilder.Entity("TL.ExemploCQRS.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").ValueGeneratedNever();
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnType("bit");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasDefaultValue("User").HasColumnType("nvarchar(50)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("IX_Users_Email");
                b.HasIndex("Username").IsUnique().HasDatabaseName("IX_Users_Username");
                b.ToTable("Users");
                b.HasAnnotation("QueryFilter", "u => !EF.Property<bool>(u, \"IsDeleted\")");
            });
#pragma warning restore 612, 618
        }
    }
}
